export const ADD_MASTER = "ADD_MASTER";
export const UPDATE_MASTER = "UPDATE_MASTER";
export const DELETE_MASTER = "DELETE_MASTER";
export const ADD_DETAIL = "ADD_DETAIL";
export const UPDATE_DETAIL = "UPDATE_DETAIL";
export const DELETE_DETAIL = "DELETE_DETAIL";